### PR TITLE
Add VectorLogoZone as a source

### PR DESCRIPTION
**Pull request by fileformat**
I don't have Sketch, so I couldn't do a complete end-to-end test, but the API results look right as far as I can tell.  Just to be sure I have the right values for the structure:
* name: text that will be searched (not necessarily unique)
* shortname: name stripped to alphanumeric (unique)

I had dependency problems with pino while running locally, but didn't want to change unrelated things.

You may want to bump MAX_RESULTS (or requery with startsWith instead of indexOf), since some common queries return too many results (for example "google")

I also noticed that shortname is not unique for instantlogos since it has files that differ only by case (for example: Zippo.svg and zippo.svg)

And the demo site URL in the README is down.

### CODE REVIEW

**Comment by fileformat** [comment]
Toby:
Is there anything you want me to do to get the PR merged?
Thanks,
Andrew

**Comment by soulchild** [comment]
@fileformat, sorry for the late response. I think this looks good, but I don't like having the complete vectorlogozone repo checked out into the `logos` directory, because there's a full web application and other stuff included. I believe doing some sort of sparse checkout is not easy with Git, but maybe you could try looking for possible solutions?

**Comment by fileformat** [comment]
No problem, PR updated.  I've done git sparse checkout before,  I had just mimicked the way you did the other sources.  

Note: you will need to be on recent version of git: I tested with v2.20.1

**Comment by soulchild** [comment]
LGTM. Thanks for the effort!

**Pull request merged**
